[env]
GOPRIVATE = "github.com/hashicorp"
EDITOR = "nano"

# How many history lines to load in memory
# For all practical purposes, this is infinite
HISTSIZE = 999999999

# How many history lines to save to disk
# For all practical purposes, this is infinite
SAVEHIST = 999999999

[tools]
nodejs = "22.3.0"
golang = "1.22.5"
terraform = "1.9.0"
vault = "1.13.2"
nomad = "1.5.7"
github-cli = "latest"
awscli = "latest"
jq = "latest"
python = "latest"
azure-cli = "latest"
gomplate = "latest"
"go:github.com/hashicorp/cloud-personal-dev-env/prdectl" = "latest"
envsubst = "latest"
yarn = "latest"
yq = "latest"
jsonnet = "latest"
