[vars]
email = "r.taiidani@gmail.com"
zsh_addons_path = "/usr/share/zsh/plugins"

[bootstrap]
config_roots = ["bundles/global", "bundles/linux"]

[dotfiles]
"~/.config/mise/config.toml" = "~/.dotfiles/.config/mise-config/config.toml"
"~/.zshrc" = "~/.dotfiles/zshrc"

[bootstrap.packages]
"brew:mise" = "latest"
"brew:zsh-autosuggestions" = "latest"
"brew:zsh-history-substring-search" = "latest"
"brew:zsh-syntax-highlighting" = "latest"
