[env]
EDITOR = "nano"
SSH_AUTH_SOCK = "/home/rnixon/.1password/agent.sock"

[tools]
1password = "latest"
awscli = "latest"
"aqua:SuperCuber/dotter" = "latest"
github-cli = "latest"
go = "latest"
goreleaser = "latest"
jq = "latest"
node = "25.6.1"
terraform = "1.14.3"
vault = "1.21.2"
