[vars]
email = "ryan.nixon@ibm.com"
zsh_addons_path = "/opt/homebrew/share"

[bootstrap]
config_roots = ["bundles/global", "bundles/macos", "bundles/work"]

[bootstrap.packages]
"brew:docker" = "latest"
"brew:mise" = "latest"
"brew:docker-buildx" = "latest"
"brew:docker-completion" = "latest"
"brew:docker-compose" = "latest"
"brew:zsh-autosuggestions" = "latest"
"brew:zsh-history-substring-search" = "latest"
"brew:zsh-syntax-highlighting" = "latest"
"brew-cask:1password" = "latest"
"brew-cask:espanso" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:lm-studio" = "latest"
"brew-cask:tuna" = "latest"
"brew-cask:zed" = "latest"

[bootstrap.macos.finder]
show_pathbar = true

[bootstrap.macos.trackpad]
tap_to_click = true

[bootstrap.macos.defaults]
"com.apple.finder" = { AppleShowAllFiles = true }
