[settings]
env_shell_expand = true

[env]
EDITOR = "nano"
SSH_AUTH_SOCK = "$HOME/.1password/agent.sock"

[tools]
"aqua:SuperCuber/dotter" = "latest"
"aqua:github/copilot-cli" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
awscli = "latest"
github-cli = "latest"
go = "latest"
goreleaser = "latest"
jq = "latest"
node = "25.6.1"
terraform = "1.15.8"
opencode = "latest"
"http:miren" = { version="v0.12.1", url = 'https://api.miren.cloud/assets/release/miren/{{ version }}/miren-{{os(macos="darwin")}}-{{arch(x64="amd64")}}.tar.gz' }
