[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[settings.npm]
bun = true

[env]
EDITOR = "nano"
SSH_AUTH_SOCK = "/home/rnixon/.1password/agent.sock"

[tools]
"aqua:SuperCuber/dotter" = "latest"
"aqua:github/copilot-cli" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
1password = "latest"
awscli = "latest"
bun = "latest"
ffmpeg = "latest"
github-cli = "latest"
go = "latest"
goreleaser = "latest"
jq = "latest"
node = "25.6.1"
terraform = "1.14.3"
vault = "1.21.2"
