[dotfiles]
"~/.docker/config.json" = ".docker/config.json"
"~/.agents/skills/coder" = ".agents/skills/coder"
"~/.agents/skills/jira" = ".agents/skills/jira"
"~/.agents/skills/mail" = ".agents/skills/mail"
"~/.agents/skills/slack" = ".agents/skills/slack"
"~/Library/Application Support/com.mitchellh.ghostty/config" = "Library/Application Support/com.mitchellh.ghostty/config"
"~/Library/Application Support/espanso" = { source = "Library/Application Support/espanso", type = "symbolic" }
"~/.config/mise/config.toml" = ".config/mise-config/config.toml"
"~/.zshrc" = { source = "zshrc", mode = "template" }
