[dotfiles]
"~/.config/mise/config.toml" = ".config/mise-config/config.toml"
"~/.zshrc" = "zshrc"
"~/Library/Application Support/com.mitchellh.ghostty/config" = "Library/Application Support/com.mitchellh.ghostty/config"
