[bootstrap.packages]
"brew:docker" = "latest"
"brew:docker-buildx" = "latest"
"brew:docker-completion" = "latest"
"brew:docker-compose" = "latest"
"brew:hashicorp/internal/docker-credential-doormat" = "latest"

[dotfiles]
"~/.docker/config.json" = "work/config.json"
