[helpers]

[default]
depends = []

[default.files]
".config/git/excludes" = "~/.config/git/excludes"
".config/opencode/opencode.json" = "~/.config/opencode/opencode.json"
".opencode/skills/gh-cli" = "~/.opencode/skills/gh-cli"
".opencode/skills/go" = "~/.opencode/skills/go"
".opencode/skills/mise" = "~/.opencode/skills/mise"
".opencode/skills/obsidian" = "~/.opencode/skills/obsidian"
"mise.toml" = "~/.config/mise/config.toml"
gitconfig = "~/.gitconfig"

[default.variables]
email = "r.taiidani@gmail.com"
zsh_addons_path = "/usr/share/zsh/plugins"

[home]
depends = ["default"]

[home.files]
".claude/settings.local.json" = "~/.claude/settings.local.json"
".opencode/skills/dependabot-merger" = "~/.opencode/skills/dependabot-merger"
zshrc = "~/.zshrc"

[work]
depends = ["default"]

[work.files]
".opencode/skills/coder" = "~/.opencode/skills/coder"
".opencode/skills/daily-routine" = "~/.opencode/skills/daily-routine"
".opencode/skills/jira" = "~/.opencode/skills/jira"
".opencode/skills/mail" = "~/.opencode/skills/mail"
".opencode/skills/slack" = "~/.opencode/skills/slack"
".ssh/config" = "~/.ssh/config"
"mise.work.toml" = "~/.mise.toml"
"zshrc.work.zsh" = "~/.zshrc"

[crc]
depends = ["work"]

[crc.files]
".crc/crc.json" = "~/.crc/crc.json"
".testcontainers.properties" = { target = "~/.testcontainers.properties", type = "symbolic" }

[settings]
default_target_type = "automatic"
