includes = []
packages = ["default", "work", "macos", "crc"]

[files]
"Library/Application Support/com.mitchellh.ghostty/config.work" = "~/Library/Application Support/com.mitchellh.ghostty/config"

[variables]
email = "rnixon@hashicorp.com"
zsh_addons_path = "/opt/homebrew/share"
