#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Ryan Nixon"
email = "{{vars.email}}"

[ui]
editor = "zed --wait"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[git]
sign-on-push = true
